### ISSUE TITLE
Add Windows set up process

### ISSUE THREAD

**Issue by Magissia** [Laverna/laverna#17]
Hello, the setup process works on linux, no problem, but node.js being new and not obvious to use (at least on windows) it could be a good idea to include windows installation instructions too.

**Comment by bkjohnson** [comment]
I agree with this - I'm currently having problems installing on Windows.  I've followed the instructions in the README but when I open laverna/app/index.html I'm just stuck with "Loading...".  If I open Chrome Dev Tools, I see that I have 20 errors:
![image](https://cloud.githubusercontent.com/assets/2008881/14582967/a061d54a-03d9-11e6-9c67-a15d6e426c94.png)

Does anyone have any suggestions for how to successfully build/run on Windows?  I didn't see any errors with bower or gulp, so I don't know what the problem is.
