### ISSUE TITLE
License Laverna under the AGPL

### ISSUE THREAD

**Issue by pquentin** [Laverna/laverna#194]
Was the GPLv3 license chosen on purpose? AGPL is recommended for web apps as simply hosting Laverna wouldn't trigger the copyleft provisions.

http://en.wikipedia.org/wiki/Affero_General_Public_License

**Comment by liweitianux** [comment]
Hello,

I saw the news about [GPL lawsuits](http://opensource.com/law/14/7/lawsuit-threatens-break-new-ground-gpl-and-software-licensing-issues)[1] some time ago. Just for your information.

Personally, I prefer the MIT/BSD licenses for the simplicity and permissiveness. Thanks!

[1] [Lawsuit threatens to break new ground on the GPL and software licensing issues](http://opensource.com/law/14/7/lawsuit-threatens-break-new-ground-gpl-and-software-licensing-issues)

**Comment by JulR43** [comment]
**To summurize, all licenses have its purpose :**

MIT/BSD/Apache are very permissive to have the widely diffusion/adoption.
(Apache is more business friendly : copyrights, patents, trademark... must be preserved)
LGPL/MPL : only your core work and modifications on itself must be of the license, but not other softwares.
AGPL/GPL : all derived/larger work must be of the license that use your work.
(AGPL adds a network clause)

I have grouped close licenses to simplify, but there are a few differences between them.
 
**Consequences and potentials risks**

Very permissive licenses *can* allow a good expansion of the utilization, but a potential bigger player can appropriate your work and "stifle" you.

However, a restricitve license *can* limit the adoption of your work, but have large guarantees for the future : all you have done will always be accessible to everyone.

**Finally**, there isn't **1** right decision, you must mesurate the pros and cons.
Examples : (GNU/)Linux (GPL) and BSD : Apple incorporates code of BSDs into XNU (open source core of MacOSX) but several components are closed source while Google **must** publish all changes on Linux kernel, that are used notably in Firefox OS.

Chromium/Android are permissive BSD and Apache to have the widest adoption : bigger community and influence. Concurrence risks that benefits of it to become a bigger threat are small because they have a (much) smaller developer and user community (Opera, CyanogenMod...) and are dependent.

Libraries use often LGPL, a compromise to have advantages of both permissive/restricitve licenses.

**Comment by wwwredfish** [comment]
We re-licensed the app to MPL-2.0 since it is something between free software and open-source.

**Comment by sheafferusa** [comment]
Boss, but, unfortunately, with respect to this particular application (as much of it is client side anyways), changing it into MPL wouldn't be much different than GPL. Since essentially, both are anyways copy-left license. Yet, anyways, if that's what has been your decision, I respect it. Although, I wished it were MIT or BSD.

**Comment by j8r** [comment]
MPL is a good choice, nice compromise between keeping the derivative work open for everyone and the freedom of use.

**Comment by pguth** [comment]
:+1:
