### ISSUE TITLE
Math equation transform not properly

### ISSUE THREAD

**Issue by ChenLiZhan** [Laverna/laverna#239]
Hello, everyone. I tried to transform some equations which are the following in Laverna:

1.  ```$$ \text{ED}_{t+1} = f(\text{ED} $$```

2.  ```$$ \text{ED}_{t+1} = f(\text{ED}, \text{ED}, \text{ED}_{t-2}, \text{ED}_{t-3},\dots, \text{error}) $$```

The first equation can transform in Laverna properly but the second one cannot. Can anyone point out what is the problem there? When I puts ```<div>``` tags around the second equation, it properly transform. I'm confuse about what happen?

Thanks for reply me 😃

**Comment by cben** [comment]
I know what's happening.  Laverna is simply transforming markdown -> html and then running MathJax on the HTML.
Your second equation contains several `_`s which the markdown parser takes as start/end of emphasis.  Note italic portions in rendering:
![55afd61c244f05-33463817](https://cloud.githubusercontent.com/assets/273688/8832562/7f118dcc-30b2-11e5-8cc2-add40cd554e8.png)
This `<em>...</em>` structures throws MathJax off and it doesn't render.

[The reason you don't hit it all the time with `a_b` etc. is that Laverna's markdown parser uses GFM-like tightened rule for `_` — it doesn't delimit emphasis when it's adjacent to a letter on either(?) side — but in this case you had `{..}_{...}`.]

The common fixes to this situation are:
 1. Teach the markdown parser to not parse inside math.  Googling "PageDown math" it seems nobody did that yet.
 2. First find math and replace with some markdown-neutral placeholder; convert markdown->HTML; replace placeholder with math; run MathJax.
    This is the approach [used by Stack Exchange](http://stackoverflow.com/a/11231030/239657), copied by several projects e.g. [ipython](https://github.com/ipython/ipython/pull/2349).
 3. First find math and render to HTML; markdown processor should pass the HTML through with no modification.  Fully rendering to HTML is a problem since MathJax is asynchronous (would be OK with KaTeX) but it's enough to just wrap the math with some tag to stop markdown parsing and let MathJax deal with them later.  This approach is IMHO cleanest.

The last option can be invoked manually: type
```
<div>\[ \text{ED}_{t+1} = f(\text{ED}, \text{ED}, \text{ED}_{t-2}, \text{ED}_{t-3},\dots, \text{error}) \]</div>
```
and it'll render!  (single-backslash `\[...\]` is what MathJax is actually looking for; it had to be `\\[...\\]` normally so that PageDown escape processing turns it into single backslash but here it doesn't do backslash processing)

**Comment by wwebfor** [comment]
Wow @cben. Thank you for solutions. I think we solved the problem with the first approach by neutralizing special characters inside of Mathjax expressions.

**Comment by cben** [comment]
Yes, noticed your patch after writing.
It looks quite good but I'm not sure the neutralizing covers all bases.

Specifically, `*` (while rare in math) can cause the same problem.
Pagedown doesn't treat simple `a*b*c` nor `a * b * c` as italics but `\\[ \hat{a}*b*\hat{c} \\]` triggers it.

And I think many other markdown constructs inside math will be a problem.  E.g.
`\\[ [\frac{a}{b}+\frac{c}{d}](x-y) \\]` becomes a link.

I think the `<div>` (or maybe better span) solution is cleanest way to stop all markdown parsing.

I've tried to test your code; after some fighting with npm I've got laverna running(*) but I'm getting "[Math processing error]"s all around.  And at tip of `dev` I'm still getting those errors, AND the escaped `&95;` etc are visible in the output.  Screenshot:
![math - all notes - laverna](https://cloud.githubusercontent.com/assets/273688/8873072/a5eef72c-320b-11e5-825b-120c62e910ba.png)
Perhaps I'm doing something wrong.

(*) It's worth adding to the README after building that you have to run a web server, file:// doesn't work.

**Comment by wwebfor** [comment]
Ah, I see. You are right. I know how to solve the bug which converts "#" symbols to links but I am not sure about others.

**Comment by wwebfor** [comment]
Perhaps you can solve the problem with "Math processing error" by executing ```grunt serve``` in terminal and opening "http://localhost:9000" in your browser.

**Comment by cben** [comment]
Run grunt serve (BTW it should be in the README)
but the error is still there. Fetched backtrace in the console:

> MathJax.Hub.lastError
TypeError: MathJax.OutputJax[c.outputJax].Process is not a function
    at Object.MathJax.Hub.processOutput
(http://localhost:9000/bower_components/MathJax/MathJax.js?config=TeX-AMS-MML_HTMLorMML:19:39411)
    at Function.CALLBACK.execute
(http://localhost:9000/bower_components/MathJax/MathJax.js?config=TeX-AMS-MML_HTMLorMML:19:3082)
    at cb (http://localhost:9000/bower_components/MathJax/MathJax.js?config=TeX-AMS-MML_HTMLorMML:19:2659)
    at Function.AFTER
(http://localhost:9000/bower_components/MathJax/MathJax.js?config=TeX-AMS-MML_HTMLorMML:19:6543)
    at Object.MathJax.Hub.processError
(http://localhost:9000/bower_components/MathJax/MathJax.js?config=TeX-AMS-MML_HTMLorMML:19:40385)
    at Object.MathJax.Hub.processOutput
(http://localhost:9000/bower_components/MathJax/MathJax.js?config=TeX-AMS-MML_HTMLorMML:19:39752)
    at Function.CALLBACK.execute
(http://localhost:9000/bower_components/MathJax/MathJax.js?config=TeX-AMS-MML_HTMLorMML:19:3082)
    at cb (http://localhost:9000/bower_components/MathJax/MathJax.js?config=TeX-AMS-MML_HTMLorMML:19:2659)
    at Function.AFTER
(http://localhost:9000/bower_components/MathJax/MathJax.js?config=TeX-AMS-MML_HTMLorMML:19:6543)
    at Object.MathJax.Hub.processError
(http://localhost:9000/bower_components/MathJax/MathJax.js?config=TeX-AMS-MML_HTMLorMML:19:40385)

Tried to use MathJax/unpacked/MathJax.js to get a non-minimized backtrace
but bower_components/ doesn’t contain the unpacked/ dir
and substituting my own MathJax checkout dir the error disappeared —
both with MathJax/unpacked/ and MathJax/, so it’s not a minimization
heisenbug but a bower problem.
(assuming it’s reproducible and not some my-machine problem)
​

2015-07-24 14:33 GMT+03:00 Wwebfor <notifications@github.com>:
