### ISSUE TITLE
What if laverna goes out of service?

### ISSUE THREAD

**Issue by castor-troy** [Laverna/laverna#292]
I see that there isn't much progress in terms of development in Laverna. I mean the last update was over a year ago. Can I be able to export notes and use Laverna offline when it goes out of service?

**Comment by wwwredfish** [comment]
Thanks for your interest in Laverna. Currently we are working on dev branch, and as soon as it's more or less stable we will merge it with master branch. You can always clone Laverna to your server/computer and use it like that. So even if the website goes down you will still be able to use it, because all data is stored on client-side. Using remotestorage is a good idea to synchronize your notes on laverna.cc and on your computer.

**Comment by skddc** [comment]
Btw, still a bounty open for upgrading/fixing RS support: https://www.bountysource.com/issues/27002492-update-fix-remotestorage-support ;)
