### ISSUE TITLE
Rendering issues

### ISSUE THREAD

**Issue by claell** [Laverna/laverna#302]
I have this test MultiMarkdown note and it showed some rendering issues, mainly some latex equations:

Test is from http://markdown-here.com/features.html

**Comment by wwebfor** [comment]
It's because some of those MathJax expressions in the example have backslashes and square braces before $. They aren't necessary if I'm not mistaken. If instead of this:
```mathjax
$\[ \left( \sum_{k=1}^n a_k b_k \right)^2 \leq \left( \sum_{k=1}^n a_k^2 \right) \left( \sum_{k=1}^n b_k^2 \right) \]$
``` 

You write this:
```mathjax
$ \left( \sum_{k=1}^n a_k b_k \right)^2 \leq \left( \sum_{k=1}^n a_k^2 \right) \left( \sum_{k=1}^n b_k^2 \right) $
```

It should render the expression properly.

**Comment by claell** [comment]
Ah, that is probably the reason. But if they can be used (even if not necessary), wouldn't it be useful to have them rendered correctly as well?

**Comment by wwebfor** [comment]
After a lot of consideration, we have decided not to implement this. It's all because it is absolutely unnecessary to have both `$` and `\[` symbols.

**Comment by claell** [comment]
Is it too complicated to implement it? I would expect that any valid syntax is rendered correctly.

**Comment by wwebfor** [comment]
It's because this syntax `$\[` is using two delimiters which is absolutely unnecessary. If I am not mistaken, the correct syntax is to use one of the delimiters not two ([source][1]).

Currently we support only `$` as the delimiter. We could of course add another delimiter but it is so much easier to have just `$` as a delimiter and focus on other tasks at hand.

[1]: https://mathjax.readthedocs.org/en/latest/options/tex2jax.html

**Comment by claell** [comment]
Alright. I understand the decision. However it might be useful to also be able to different an equation using the `\[` delimiter.
