### ISSUE TITLE
[desktop app] Can't submit Dropbox login credentials

### ISSUE THREAD

**Issue by WTurunen** [Laverna/laverna#328]
Syncing to Dropbox app, I can't sign in to Dropbox. The _Sign in_ button remains disabled when the email address and password are entered. 

Also the placeholder text stays while editing the fields.

![login](https://cloud.githubusercontent.com/assets/3134372/11839109/febf2ea8-a3f3-11e5-9f19-f68117212781.PNG)

**Comment by wwebfor** [comment]
What OS do you use?

Maybe I'm wrong, bug judging from the screenshot, it seems like Dropbox "Sign in" page hasn't finished loading.

**Comment by WTurunen** [comment]
I'm on Windows 10 64bit. 

I've waited for several minutes with a 100M connection and the button remains disabled. The Dropbox-icon and _forgot password_ links work.

**Comment by wwebfor** [comment]
I see. We will try to figure out what is causing the problem later. Thanks for your bug report.

**Comment by claell** [comment]
It seems like the fields are not recognized as filled in. You could try to use tab to navigate from one field to another instead of using the mouse. Maybe then it is recognized?

**Comment by WTurunen** [comment]
I tried using tab, as I usually do, and with mouse, but no changes - the button remains disabled either way.

**Comment by claell** [comment]
Alright, thanks for trying.

**Comment by arulk** [comment]
I have the same issue but on Mac OSX .  I am unable to enter my dropbox authorization credentials.

**Comment by varod** [comment]
I have the same on Linux Ubuntu 15.10 64bits but only on desktop version. Dropbox sync is working on web version.

**Comment by zweicoder** [comment]
@wwebfor Having experienced this problem I spent some time working on it to find out why it happens. `AssertionError: path must be a string` was thrown by the Dropbox OAuth page, meaning the Javascript stuff being loaded by the site was conflicting with `Electron` / `Node`'s `require` method.

Since it's loaded by an external site we can't inject stuff to override the `require` methods as is being done in `app/index.html`. The simplest way is to disable `node-integration` altogether when constructing `BrowserWindow` by setting it to `false` (Not sure whether this breaks anything but the tests pass..)

I have also made an `Electron` AuthDriver that only disables `node-integration` on the OAuth page, although you will have to add `https://www.dropbox.com/1/oauth2/redirect_receiver` to your redirect URI in the Dropbox Console. 

Tell me if either one of these is fine and I'll send in a PR if needed :)

**Comment by wwebfor** [comment]
@zweicoder we left ``node-integration`` enabled because of the issue #262, so it is preferable to have access to Nodejs API.

I guess the safest choice is to disable ``node-integration`` on all pages except for the pages which contain strings like ``localhost`` or ``file://``. Although, I am not sure if it is possible to do that.

**Comment by mmdavid** [comment]
Hi. Did you fix this bug? I'am having the same problem. Papers3 Version 3.3.3 (361) on  mac OSX 10.13.1

**Comment by ajn123** [comment]
Still have this same problem on Mac OSX

**Comment by funilrys** [comment]
Hi @ajn123 @mmdavid @zweicoder @valvin1 @arulk @claell @WTurunen 

Unfortunately, this issue will never be fixed here.

Please report to https://github.com/Laverna/laverna/issues/971#issuecomment-411423965 for the current state of this project and https://github.com/encryptic-team/encryptic for the future of this project.

Have a nice day/night.

Cheers,
Nissar
