### ISSUE TITLE
Encryption Error with New Version

### ISSUE THREAD

**Issue by 19kestier** [Laverna/laverna#344]
Ever since the laverna.cc site switched to the new look, I can't view my notes! I know my password and remember my encryption settings. When I try to load my notes, it just gives a a generic "Encryption Error".

![screenshot 2015-12-28 at 10 10 10 pm](https://cloud.githubusercontent.com/assets/4749568/12029062/3a48509c-adb0-11e5-8fc6-8d4122f8a18d.png)

I have some important notes on Laverna that I'd really like to get back. I also had Laverna set up to sync with Dropbox, if this helps.

Is there any way to retrieve my lost notes?

**Comment by 19kestier** [comment]
When I paste the contents of my encrypted notes in the SJCL demo page, it tells me the code is invalid JSON.

![screenshot 2015-12-28 at 10 20 24 pm](https://cloud.githubusercontent.com/assets/4749568/12029114/563f142e-adb1-11e5-9c72-72be0eebff3d.png)

Here is my Dropbox sync folder: https://www.dropbox.com/sh/qe71bbksq7b1b54/AADW7MFwkR-vGpAPig13P_cUa?dl=0

**Comment by wwebfor** [comment]
Hi, thank you for reporting the issue. On SJCL demo it says invalid JSON probably because it is invalid JSON. You can try to access your notes on old version which is located on https://laverna.cc/dist

**Comment by 19kestier** [comment]
There is some sort of a bug in the new version, because when I loaded the page suggested by @wwebfor my notes loaded fine. Thanks so much!

**Comment by wwebfor** [comment]
Alright. For now, you can use the old version. In the meantime we will work on solving this bug. When we fix the bug, we'll notify you. We are sorry if it caused you any inconveniences.

**Comment by 19kestier** [comment]
If you need any info to fix this, I'll be glad to help!

On Tue, Dec 29, 2015 at 12:50 PM, Wwebfor <notifications@github.com> wrote:

> Alright. For now, you can use the old version. In the meantime we will
> work on solving this bug. When we fix the bug, we'll notify you. We are
> sorry if it caused you any inconveniences.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Laverna/laverna/issues/344#issuecomment-167842787>.
>



-- 
Kenny Stier <https://19kestier.github.io/>

**Comment by p6ril** [comment]
I have a similar issue, ever since the interface has changed the system refuses to show me my notes. Initially I've had a problem with the redirect URI on Dropbox which has apparently changed from https://laverna.cc/dropbox.html to https://laverna.cc/app/dropbox.html. I've fixed this in Dropbox. However no change once I import my settings I get a blank page with no notes and no error message whatsoever. The link to the previous version of Laverna doesn't seem to work thus I'm stuck and I can't access my notes anymore :( It only I could acces a previous version of the system that'd be great

**Comment by wwebfor** [comment]
@p6ril the previous version can be accessed from here laverna.cc/dist

**Comment by p6ril** [comment]
that's what I've tried as it was mentioned earlier in the discussion but all I get there is a blank page at this address ...

**Comment by wwebfor** [comment]
How about laverna.cc/old.html?

**Comment by p6ril** [comment]
same thing I get the green background and turning arrows then nothing but a blank white page

**Comment by wwebfor** [comment]
OK, we will start working on this issue starting from tomorrow.

**Comment by p6ril** [comment]
hang on I've changed browser and it works with laverna.cc/dist. May be a cache issue. Weird since I've tried cleaning the browser cache and cookies

**Comment by p6ril** [comment]
yes! I'm in thanks

**Comment by wwebfor** [comment]
You are welcome :)

**Comment by wwebfor** [comment]
Hi @19kestier

We've changed encryption module a little and published a pre-release. Can you test it (it's available at https://laverna.cc/nightly)?

If you are able to read your notes, please, back them up and change your password.

**Comment by wwebfor** [comment]
@p6ril,

Your issue is completely different. It is happening because in the new version the app tries to find your notes on Dropbox in a different folder. All you have to do is to create a new folder in `Apps/Laverna` called `notes-db`.

After creating the folder, you need to move `notebooks`, `notes`, `tags` folders to `Apps/Laverna/notes-db`.

Apparently you are using your own Dropbox App key. In that case, you need to change `Apps/Laverna` to `Apps/` + the name of your app on Dropbox.

**Comment by p6ril** [comment]
@wwebfor I did exactly as you say and problem solved ... thanks you rock !
