### ISSUE TITLE
Update README for Installation: cd laverna

### ISSUE THREAD

**Issue by jlpoolen** [Laverna/laverna#545]
The current README for installation has:

> To install, do the following:
1. Clone repository:

>$ git clone git@github.com:Laverna/laverna.git

>2. Ensure you have the node.js platform installed. See OS-specific instructions on their website.
>3. Ensure you have the bower and gulp packages installed (locally and globally):

>$ npm install bower
>$ npm install gulp

>4. Install Laverna's dependencies:

>$ npm install
>$ bower install
>$ (cd test && bower install)

>5. Build minified version of Laverna:

>$ gulp build

>6. Start Laverna:

>$ gulp

At some point after cloning the source and before step 4 "Install Laverna's dependencies", you need to 

> cd laverna

**Comment by JerJohn15** [comment]
@jlpoolen 

I think it was assumed by the original author that users should be familiar with using github and the command line. With that being said though, I think that it could be useful to include your suggestion, so that it is easier to get started for those that are new to configuring projects from a repository. I can go ahead and make a pull request.

**Comment by JerJohn15** [comment]
@wwebfor  @jlpoolen 

My Pull Request was accepted, so this issue can be closed now.

**Comment by jlpoolen** [comment]
Thank you!
