### ISSUE TITLE
Browser console spewing "Refused to get unsafe header "ETag"" with remoteStorage

### ISSUE THREAD

**Issue by clark800** [Laverna/laverna#76]
I'm running Laverna version 0.5.0, reStore version 0.2.0, and Chrome 34.0.1847.131. The remoteStorage is syncing to the server, but the javascript console is spewing the error: "Refused to get unsafe header "ETag"" and the sync spinner never stops spinning.

**Comment by skddc** [comment]
This might be solved in reStore 0.3.0. Could someone try again?

(Also, someone told me that Laverna doesn't sync his data across devices, because it keep some kind of session and you can only see the data from the device/browser you connected your storage on. That would be against the idea of remoteStorage, of course, but I don't know if that's intentional or a bug.)

**Comment by wwwredfish** [comment]
Can someone check if the issue is solved in the new version?

**Comment by skddc** [comment]
I can't see the message anymore and Chrome syncs fine for me.

@clark800 @andtheWings Could you verify?

**Comment by clark800** [comment]
Sorry, I'm not working with this project anymore.

**Comment by andtheWings** [comment]
The behavior is different now, but it still doesn't sync. The console keeps reporting: "'change' handler failed:  Error: You must provide a name for the channel."

I've personally switched to using dropbox with encryption, which is working great.

**Comment by wwebfor** [comment]
The issue is resolved.
