### ISSUE TITLE
Laverna DropBox sync to stop working in September?

### ISSUE THREAD

**Issue by romu70** [Laverna/laverna#805]
Hello,
I've just receveid an email from DropBox saying at the end of Septembre, Laverna sync may not work anymore due to API changes.

Is the Laverna code already ready for those changes?

**Comment by dayfuaim** [comment]
Confirm it.
Hope Laverna to not drop DropBox after 28.09.

**Comment by claell** [comment]
#776 seems to already point this out. But I agree that this should be fixed soon!

**Comment by RebelCoderRU** [comment]
Laverna has not been updated since 30 June of 2016, which is more then a year. I wonder if this project is dead ? I am using it on my Linux and Android devices. Don't know of any other project, that clean and simple and open source.

**Comment by strangefreeworld** [comment]
@RebelCoderRU check out Standard Notes (standardnotes.org) it may do everything you need and it works on both Linux and Android.  I am looking at migrating to that right now because I haven't seen any Laverna updates lately.  I like this software but Dropbox going away is a problem to me.

**Comment by dayfuaim** [comment]
@strangefreeworld "Standard Notes" is good.
But the only thing needed (Advanced Markdown editor) is paid in "Extended":
![2017-08-14 15-53-28](https://user-images.githubusercontent.com/1274699/29272472-e56dd1b8-8108-11e7-9c53-4e33096968af.png)
So, at least right now, it's not an option for me.
It's interesting, is the Laverna Dev reading the issues, huh?

**Comment by romu70** [comment]
There is also Leanote (http://leanote.org/), fully open source, but requires Mongo as backend.

**Comment by RebelCoderRU** [comment]
Looked at Leanote and Paperwork. Both are just not Laverna. Laverna is the best so far, and it is sad to see it has been abandoned.

**Comment by dayfuaim** [comment]
Looked at Paperwork. For note-taking app it's just little too big and complex: installing a server with PHP and such stuff is not what's needed.
Laverna is best (at least so far) of all.

**Comment by romu70** [comment]
Look at TagSpaces guys, it should fulfill your needs. It's open source.

**Comment by wwebfor** [comment]
Hi guys,
The project hasn't been abandoned. I just didn't & don't have time for a while, but I should be able to re-implement  Dropbox thing before the deadline.

**Comment by Kaleidosko** [comment]
Hi wwebfor,
would be awesome if you also could have a look on the Linux version because there I could not setup dropbox sync. When I try to authorize dropbox a green popup is shown and after a moment Laverna is closed completely :( On Windows and Android it seems to sync.

Greetings

**Comment by shaypal5** [comment]
Just putting the Dropbox v1 to v2 migration guide link here as reference:
https://www.dropbox.com/developers/reference/migration-guide

(also, I'll try to give help with migration, if needed)

**Comment by talklittle** [comment]
Laverna has been using this Dropbox v1 API shim for Bower: https://github.com/lavelle/dropbox (which is now a 404, so forked to https://github.com/talklittle/dropbox) -- Called `dropbox-build` on Bower.

The most straightforward way of migrating to v2 would be generating a similar shim that could be dropped into Laverna with minimal build configuration changes. Unfortunately I don't know how to generate the shim.

Otherwise using the Dropbox SDK v2 directly from NPM, would require NPM + Webpack, which happens to be implemented in Laverna's [dev branch](https://github.com/Laverna/laverna/tree/dev). However the dev branch appears to be far from usable in production in its current state. (Would love to be proven wrong on this!)

So I'm not exactly sure what's the best way forward.

**Comment by ArtursO** [comment]
Is anyone here capable of submitting a PR for the dropbox issue?

**Comment by wwebfor** [comment]
It should be fixed now.
