### ISSUE TITLE
Unable to Sync

### ISSUE THREAD

**Issue by hlrossato** [Laverna/laverna#975]
I've created some notes some days ago and synced with my Dropbox account and at that time everything was working ok. Now, I've tried to get my notes back but I can't. I've also tried to create another app on Dropbox and sync some new notes but unsuccessfully.

I'm getting this error:

<img width="1440" alt="image" src="https://user-images.githubusercontent.com/2665019/44626832-a1e2b300-a91b-11e8-9154-84669dca9cbf.png">

Anyone facing the same issue? Any fix for this? Am I doing something wrong?

**Comment by daed** [comment]
It looks like "Validation failed" can happen when the notes fail to successfully decrypt.

Are you doing all of this on the same computer?  When you say that you created another app on Dropbox, what do you mean by that?  How, specifically, did you do that?

Did you export your settings at any point before this occurred?

**Comment by hlrossato** [comment]
I've tried to access the notes from the laptop I've created them but also from another laptop. I've used a password for encryption but didn't work. I didn't export any settings. Should I have had exported them? By the another Dropbox app what I meant was I've tried the same process with new notes but didn't work either.

**Comment by daed** [comment]
Your settings contain the decryption method.  You need them in addition to the password in order to view your notes.

In order to be able to use dropbox sync across multiple computers, you must first:
- Set up Laverna to use dropbox on one computer
- Export the configuration to file via the import/export menu. 
- Put that file on the second computer and import into Laverna.  After doing this, it should then work.

Sadly, this is not well documented anywhere.

**Comment by hlrossato** [comment]
Yes, I didn't export my settings at all because there was nothing on the docs talking about that. I thought it'd work based on the same password and encryption type.
Anyway, I've lost the notes :/ Thanks for your help @daed
